### ISSUE TITLE
CreateIssue button fails

### ISSUE THREAD

**Issue by drighelli** [Bioconductor/BiocWorkshopSubmit#4]
CreateIssue button fails with the following message:

`Input to asJSON(keep_vec_names=TRUE) is a named vector. In a future version of jsonlite, this option will not be supported, and named vectors will be translated into arrays instead of objects. If you want JSON object output, please use a named list instead. See ?toJSON.`

Also the interface produces the following message:
![Screenshot 2023-11-23 at 14 49 25](https://github.com/Bioconductor/BiocWorkshopSubmit/assets/22836149/c1279ea5-8439-4903-a43b-78f0695dc86f)

**Comment by LiNk-NY** [comment]
Hi Dario, @drighelli 

Thanks for reporting. This may have been due to a credentials issue. Did you set your credentials with `gitcreds::gitcreds_set()`? See the vignette for details. 

I just tested the code at https://github.com/Bioconductor/workshop-contributions/issues/73 and it worked OK. 

I will look into catching errors from `gh::gh` calls and provide a meaningful error message. Thanks!

**Comment by LiNk-NY** [comment]
Resolved in d7762cfaf0324119d86b5f3f42985eacb664b1db
